// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: ''),
    appId: '1:504924674903:web:87a00c91a4cab90a58fc12',
    messagingSenderId: '504924674903',
    projectId: 'child-safe-app-kita',
    authDomain: 'child-safe-app-kita.firebaseapp.com',
    storageBucket: 'child-safe-app-kita.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: ''),
    appId: '1:504924674903:android:8b6a282fe8219bd558fc12',
    messagingSenderId: '504924674903',
    projectId: 'child-safe-app-kita',
    storageBucket: 'child-safe-app-kita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: ''),
    appId: '1:504924674903:ios:66a08ef952fe907958fc12',
    messagingSenderId: '504924674903',
    projectId: 'child-safe-app-kita',
    storageBucket: 'child-safe-app-kita.firebasestorage.app',
    iosBundleId: 'com.example.childSafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: ''),
    appId: '1:504924674903:ios:66a08ef952fe907958fc12',
    messagingSenderId: '504924674903',
    projectId: 'child-safe-app-kita',
    storageBucket: 'child-safe-app-kita.firebasestorage.app',
    iosBundleId: 'com.example.childSafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: ''),
    appId: '1:504924674903:web:ad8df18005ca865c58fc12',
    messagingSenderId: '504924674903',
    projectId: 'child-safe-app-kita',
    authDomain: 'child-safe-app-kita.firebaseapp.com',
    storageBucket: 'child-safe-app-kita.firebasestorage.app',
  );
}